[filament:Fillamentum ABS @DQ2FP2]
renamed_from = "DeltiQ FP2 - ABS - ExtraFill (Fillamentum)"
inherits = Generic ABS @DQ2FP2; *DQ2FP2 0.4*
filament_cost = 24.27
filament_spool_weight = 229
filament_density = 1.04
filament_vendor = Fillamentum


# DeltiQ ASA filaments #

