[printer:X-MAX 3 0.8 nozzle]
inherits = *X-MAX 3*
default_filament_profile = Generic PLA @X-MAX 3 0.8 nozzle
default_print_profile = 0.40mm Fine @X-MAX 3 0.8 nozzle
max_layer_height = 0.56
min_layer_height = 0.16
nozzle_diameter = 0.8
printer_variant = 0.8
retract_length = 3

# X-Plus 3 preset
