[printer:*common*]
printer_technology = FFF
bed_shape = -107x-93,107x-93,107x93,-107x93
printer_vendor = BIBO
printer_model = BIBO2
printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_BIBO\nPRINTER_MODEL_BIBO2
printer_variant = 0.4
nozzle_diameter = 0.4
default_print_profile = 0.20mm NORMAL @BIBO2
default_filament_profile = Generic PLA @BIBO2
before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
between_objects_gcode = 
deretract_speed = 0 # By setting this value to 0 deretract used the retract_speed
extruder_colour = #FFFF00
extruder_offset = 0x0
extruder_clearance_height = 12
extruder_clearance_radius = 45
gcode_flavor = marlin
silent_mode = 0
remaining_times = 0
machine_max_acceleration_x = 1100
machine_max_acceleration_y = 1100
machine_max_acceleration_z = 100
machine_max_acceleration_e = 5000
machine_max_acceleration_extruding = 1100
machine_max_acceleration_retracting = 1100
machine_max_feedrate_x = 350
machine_max_feedrate_y = 350
machine_max_feedrate_z = 2
machine_max_feedrate_e = 25
machine_max_jerk_x = 10
machine_max_jerk_y = 10
machine_max_jerk_z = 0.3
machine_max_jerk_e = 5
machine_min_extruding_rate = 0
machine_min_travel_rate = 0
layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
max_layer_height = 0.30
min_layer_height = 0.05
max_print_height = 160
printer_settings_id =
retract_before_travel = 1
retract_before_wipe = 100%
retract_layer_change = 1
retract_length = 1.5
retract_length_toolchange = 1.5
retract_lift = 0
retract_lift_above = 0
retract_lift_below = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 20
single_extruder_multi_material = 0
toolchange_gcode = 
use_firmware_retraction = 0
use_relative_e_distances = 1
use_volumetric_e = 0
variable_layer_height = 1
wipe = 1
z_offset = 0
end_gcode = ;BIBO End GCode\nM107 ; turn fans off\nG91 ; Relative positioning\nG1 Z1 F100\nM140 S0    ; Disable heated bed\nM104 T0 S0 ; extruder T0 heater off\nM104 T1 S0 ; extruder T1 heater off\nG1 Z+0.5 X-20 Y-20 F300 ; move Z down then move print head a bit out of the way\nG28 X0 Y0 ; move X/Y to min endstops, so the head is out of the way\nG90    ; Absolute positioning\nG92 E0.0 ; Reset extruder position\nM84    ; Turn steppers off\nM117 BIBO Print complete ; Put print complete message on screen


# Intended for printers that have been modified with a 32bit mainboard or otherwise use marlin 2 firmware
