[print:0.28 mm SUPERDRAFT @Multi-extruder]
inherits = *0.28mm*; *0.4nozzle*; *Multi-extruder*
compatible_printers_condition = printer_model=~/(Mizar|A10|A20|A30|E180|Me|GiantArm|I3).*/ and nozzle_diameter[0]==0.4 and num_extruders>=2
#########################################
####### End ###print presets ########
#########################################


# When submitting new filaments please print the following temperature tower at 0.1mm layer height:
#   https://www.thingiverse.com/thing:2615842
# Pay particular attention to bridging, overhangs and retractions.
# Also print the following bed adhesion test at 0.1 layer height as well:
#   https://www.prusaprinters.org/prints/4634-bed-adhesion-warp-test
# At least for PLA, please keep bed temp at 60℃, as many Geeetech printers do not have any ABL
# So having some leeway to get good bed adhesion is not a luxury for many users


#########################################
####### Start ###filament presets #######
#########################################
