[print:0.44 mm SUPERCHUNKY (0.8mm nozzle) @M1_speed]
inherits = *0.44mm*; *0.8nozzle*; *M1_speed*
max_volumetric_speed = 20
compatible_printers_condition = printer_model=~/(M1).*/ and nozzle_diameter[0]==0.8 and num_extruders==1

# Print quality for multi-extruder printers (0.4mm nozzle diameter)
