[print:*High-speed*]
# Print presets for high-speed printers.
inherits = *common*
top_solid_layers = 3
bottom_solid_layers = 3
gap_fill_enabled = 0
default_acceleration = 5000
perimeter_speed = 230
external_perimeter_speed = 83%
solid_infill_speed = 80
infill_speed = 250
top_solid_infill_speed =100%
support_material_speed = 100
support_material_interface_speed = 50%
brim_speed = 30%
bridge_speed = 180
bridge_speed_internal = 120%
overhangs_speed = 120%
gap_fill_speed = 100
gap_fill_flow_match_perimeter = 0
thin_walls_speed = 100%
ironing_speed = 75%
travel_speed = 260
travel_speed_z = 0
first_layer_min_speed = 0
first_layer_speed = 30
first_layer_infill_speed = 0
first_layer_speed_over_raft = 30
small_perimeter_speed = 65%
max_print_speed = 300
max_volumetric_extrusion_rate_slope_negative = 0
max_volumetric_extrusion_rate_slope_positive = 0
small_perimeter_min_length = 8
small_perimeter_max_length = 25.1327
solid_infill_below_area = 0
#travel_speed = {if 120<=infill_speed<=200}200{elsif infill_speed>200}infill_speed{else}150{endif}
#perimeter_speed = {if infill_speed<60}math.ceil(round(infill_speed*0.8){elsif infill_speed>60}math.ceil(round(infill_speed*0.75)){else}60{endif}
#external_perimeter_speed = {if infill_speed<=60}math.ceil(round(infill_speed*0.5)){else}math.ceil(round(infill_speed*0.75)){endif}
#solid_infill_speed = {if infill_speed<=60}20{else}math.ceil(round(infill_speed*0.3)){endif}
#top_solid_infill_speed = {if infill_speed<=60}20{elsif 60<infill_speed<200}math.ceil(round(infill_speed*0.6){elsif 200<=infill_speed<=250}math.ceil(round(infill_speed*0.5){else}math.ceil(round(infill_speed*0.4)){endif}
#support_material_speed = {if infill_speed<60}math.ceil(round(infill_speed*0.8){elsif infill_speed>60}math.ceil(round(infill_speed*0.5){else}40{endif}
#bridge_speed = {if infill_speed<=60}math.ceil(round(infill_speed*0.5)){else}math.ceil(round(infill_speed*0.75)){endif}
#bridge_speed_internal = {if infill_speed<=60}math.ceil(round(infill_speed*1.5)){elsif 60<infill_speed<200}math.ceil(round(infill_speed*1.2){elsif 200<=infill_speed<=250}infill_speed{else}math.ceil(round(infill_speed*0.8)){endif}
#overhangs_speed = {if infill_speed<=60}infill_speed{elsif 60<infill_speed<200}math.ceil(round(infill_speed*0.9){elsif 200<=infill_speed<=250}math.ceil(round(infill_speed*0.85){else}math.ceil(round(infill_speed*0.8)){endif}
#gap_fill_speed = {if infill_speed<=60}math.ceil(round(infill_speed*0.3){elsif 60<infill_speed<150}math.ceil(round(infill_speed*0.5){elsif 150<=infill_speed<=200}math.ceil(round(infill_speed*0.6){else}math.ceil(round(infill_speed*0.65)){endif}
#thin_walls_speed = math.ceil(round(external_perimeter_speed*0.6)
#ironing_speed =  math.ceil(round(infill_speed*0.5)
#small_perimeter_speed = math.ceil(round(infill_speed*0.45)

