[print:0.3 Layer - 0,4 Nozzle]
inherits = *0.30mm*
# alias = 0.30mm DRAFT 0,4
compatible_printers_condition = nozzle_diameter[0]==0.4

#///////////////////////////////////////////////////#
#---------------# FILAMENT SETTINGS #---------------#
#///////////////////////////////////////////////////#

