[print:Fast - M5C (0.4 mm nozzle) @ANKER]
inherits = *common-M5C*
notes = PRINT_COMPATIBLE\n P_FAST\n F_PLA__Basic\n
compatible_printers_condition = printer_notes=~/.*(MACHINE_M5C_).*/ and printer_notes=~/.*(P_FAST).*/ and nozzle_diameter[0]==0.4
layer_height = 0.25
first_layer_height = 0.14
perimeters = 2
top_solid_layers = 4
bottom_solid_layers = 3
external_perimeter_acceleration = 3000
perimeter_acceleration = 5000
top_solid_infill_acceleration = 4000
solid_infill_acceleration = 4000
infill_acceleration = 5000
bridge_acceleration = 500
first_layer_acceleration = 2500
first_layer_acceleration_over_raft = 0
travel_acceleration = 5000
default_acceleration = 5000
# Speed
perimeter_speed = 250
small_perimeter_speed = 75
external_perimeter_speed = 150
infill_speed = 270
solid_infill_speed = 100
top_solid_infill_speed = 100
support_material_speed = 150
support_material_interface_speed = 100%
bridge_speed = 20
gap_fill_speed = 75
overhang_speed_0 = 15
overhang_speed_1 = 20
overhang_speed_2 = 30
overhang_speed_3 = 30
travel_speed = 500
travel_speed_z = 10
first_layer_speed = 50
first_layer_speed_over_raft = 30
max_print_speed = 500

# When submitting new filaments please print the following temperature tower at 0.1mm layer height:
#   https://www.thingiverse.com/thing:2615842
# Pay particular attention to bridging, overhangs and retractions.
# Also print the following bed adhesion test at 0.1 layer height as well:
#   https://www.prusaprinters.org/prints/4634-bed-adhesion-warp-test
# At least for PLA, please keep bed temp at 60, as many Creality printers do not have any ABL
# So having some leeway to get good bed adhesion is not a luxury for many users

