[printer:*gCreate gMax 2 Dual Chimera*]
inherits = *common*
printer_model = GMAX2DUAL
max_layer_height = 0.7
min_layer_height = 0.08
printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_GCREATE\nPRINTER_MODEL_GMAX2DUAL
start_gcode = G90\nG28\nM420 Z20\nG1 Z5 F5000\nM218 T1 X20 Y0 ; Set second extruder offset
end_gcode = M104 S0 T0 ; turn off temperature\nM104 S0 T1 ; turn off 2nd extruder\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+5, max_print_height)} F600{endif} ; Move print head up\nG1 X5 Y170 F3000 ; present print\n{if layer_z < max_print_height-10}G1 Z{z_offset+min(layer_z+70, max_print_height-10)} F600{endif} ; Move print head up\nM84 X Y E ; disable motors
bed_shape = 0x0,457x0,457x457,0x457
max_print_height = 610
default_print_profile = 0.20mm - Standard Layers @GCREATE
single_extruder_multi_material = 0
#multi tool settings
extruder_colour = #FF3333;#0000CC
extruder_offset = 0x0,20x0
retract_length_toolchange = 8,8
retract_speed = 70,70
extruder_clearance_height = 20
extruder_clearance_radius = 20

##############################################
#  SET NOZZLE DIAMETER VARIANTS PER PRINTER  #
##############################################

#these are the names and printers displayed in the drop down menus when selecting profiles

#####################################
#gMax 1.5 XT+ and gMax 1.5+ profiles#
#####################################


