[printer:gMax 1.5XT Plus - 1.0mm nozzle]
#match printer name above
inherits = *gCreate gMax 1.5XT Plus*
printer_variant = 1.0
nozzle_diameter = 1.0
max_layer_height = 0.8
min_layer_height = 0.3
#default_print_profile = 0.30mm QUALITY @0.6 nozzle MINI
#retract_length = 3.5


#################
#gMax 2 profiles#
#################

