[filament:Generic PLA]
inherits = *PLA*
filament_vendor = Generic
filament_cost = 25.4
filament_density = 1.24

# Discontinued

# [filament:3D-Fuel Standard PLA]
# inherits = *PLA*
# filament_vendor = 3D-Fuel
# filament_cost = 22.14
# filament_density = 1.24
# first_layer_temperature = 210
# temperature = 200

# [filament:3D-Fuel EasiPrint PLA]
# inherits = 3D-Fuel Standard PLA
# filament_cost = 30.44

# [filament:3D-Fuel Pro PLA]
# inherits = *PLA*
# filament_vendor = 3D-Fuel
# filament_cost = 26.57
# filament_density = 1.22
# first_layer_temperature = 220
# temperature = 215

# [filament:3D-Fuel Buzzed]
# inherits = 3D-Fuel Standard PLA
# filament_cost = 44.27
# filament_retract_lift = 0
# first_layer_temperature = 210
# temperature = 195

# [filament:3D-Fuel Wound up]
# inherits = 3D-Fuel Buzzed
# filament_cost = 44.27
# filament_retract_lift = nil
# first_layer_temperature = 215
# temperature = 210

# [filament:3D-Fuel Workday ABS]
# inherits = *ABSC*
# filament_vendor = 3D-Fuel
# filament_cost = 23.25
# filament_density = 1.04

