[print:0.55mm DRAFT @0.8 nozzle SV02]
inherits = *common*; *0.8nozzleSV02*
layer_height = 0.55
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_SOVOL.*/ and printer_notes=~/.*PRINTER_MODEL_SV02.*/ and nozzle_diameter[0]==0.8
perimeter_speed = 30
external_perimeter_speed = 25
infill_acceleration = 1000
infill_speed = 50
max_print_speed = 50
solid_infill_speed = 40
support_material_speed = 35
support_material_contact_distance = 0.25
top_solid_infill_speed = 30
external_perimeter_extrusion_width = 1
perimeter_extrusion_width = 1


## SV03 ##


## SV03 - 0.4mm nozzle

