[print:*0.8nozzleM*]
gcode_label_objects = firmware

#---------------------------------------------------------------------------------------------------------------------------
#    profiles
#---------------------------------------------------------------------------------------------------------------------------

# XXXXXXXXXXXXXXXXXXXX
# XXX--- 0.05mm ---XXX
# XXXXXXXXXXXXXXXXXXXX

