[printer_model:GMAX2DUAL2IN1]
name = gMax 2 Dual 2in1
variants = 0.5
technology = FFF
family = GMAX
#has to be named (printer)_bed.stl
bed_model = gmax2_bed.stl
bed_texture = gmax2.svg
default_materials = Generic PLA @GCREATE; Generic PETG @GCREATE; Generic ABS @GCREATE; Prusament PLA @GCREATE; Prusament PETG @GCREATE; Generic TPU 90A @GCREATE; Generic CF PETG @GCREATE; Generic CF Nylon @GCREATE; Generic CF PLA @GCREATE

thumbnail = GMAX2DUAL2IN1_thumbnail.png
