[print:*FAST*]
#SPEED
perimeter_speed = 70
small_perimeter_speed = 85%
external_perimeter_speed = 75%
infill_speed = 85%
solid_infill_speed = 70%
top_solid_infill_speed = 65%
support_material_speed = 75%
bridge_speed = 45
gap_fill_speed = 30


#############################################################################
#  SET PRINTER AND NOZZLE SPECIFIC PROFLIES (THESE SHOW INT HE DROPDOWN)    #
#############################################################################

#we can add specific changes for specific printers and nozzle sizes. Just put in conditionals
# compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_GCREATE.*/ and printer_model=~/.*GMAX2PRO.*/ and nozzle_diameter[0]==0.5


#TEMPLATE

#SPEED SETTINGS
#[print:0.10mm - Very Thin Layers @GCREATE]
#perimeter_speed = 100%
#small_perimeter_speed = 100%
#external_perimeter_speed = 100%
#infill_speed = 100%
#solid_infill_speed = 100%
#top_solid_infill_speed = 100%
#support_material_speed = 100%
#bridge_speed = 100%
#don't adjust gap speed above 30 or it causes layer shifting
#gap_fill_speed = 30

#ADVANCED
#



