[printer_model:MINI_AERO]
name = Mini Aero
variants = 0.5
technology = FFF
#bed_model = mini_bed.stl
#bed_texture = mini.svg
default_materials = Generic PLA @lulzbot; Generic PETG @lulzbot; Jessie PLA @lulzbot

thumbnail = MINI_AERO_thumbnail.png
