[print:0.08mm DETAIL @FLSUN]
inherits = *0.08mm_flsunq*; *QQSP*
compatible_printers_condition = printer_notes=~/.*PRINTER_MODEL_Q(QSP|5).*/ and nozzle_diameter[0]==0.4
bridge_acceleration = 200
bridge_speed = 20
external_perimeter_speed = 70%
first_layer_acceleration = 500
first_layer_speed = 40%
gap_fill_speed = 20
infill_acceleration = 800
infill_speed = 40
max_print_speed = 80
perimeter_acceleration = 300
perimeter_speed = 30 
small_perimeter_speed = 70%
solid_infill_speed = 95%
support_material_speed = 40
top_solid_infill_speed = 60%

# XXXXXXXXXXXXXXXXXXXX
# XXX--- 0.15mm ---XXX
# XXXXXXXXXXXXXXXXXXXX

