[print:0.15mm VASE SPEED @FLSUN]
inherits = *0.15mm_vase_flsunq*
compatible_printers_condition = printer_notes=~/.*PRINTER_MODEL_Q(QSP|5).*/ and nozzle_diameter[0]==0.4
bridge_speed = 80
bottom_solid_layers = 3
external_perimeter_speed = 60%
gap_fill_speed = 30
infill_speed = 80
perimeter_speed = 90
small_perimeter_speed = 50%
solid_infill_speed = 80%

# XXXXXXXXXXXXXXXXXXXX
# XXX--- 0.16mm ---XXX
# XXXXXXXXXXXXXXXXXXXX

