[print:0.16mm DETAIL @0.6 nozzle FLSUN]
inherits = *0.16mm_flsunq*; *0.6nozzleFLSUN*
# alias = 0.16mm DETAIL
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_FLSun.*/ and printer_notes=~/.*PRINTER_MODEL_Q(QSP|5).*/ and nozzle_diameter[0]==0.6
external_perimeter_speed = 35
infill_speed = 70
max_print_speed = 80
perimeter_speed = 40
solid_infill_speed = 60
top_solid_infill_speed = 45
infill_extrusion_width = 0.65
solid_infill_extrusion_width = 0.65

# XXXXXXXXXXXXXXXXXXXX
# XXX--- 0.20mm ---XXX
# XXXXXXXXXXXXXXXXXXXX

