[print:*Q5*]
bridge_acceleration = 1000
default_acceleration = 800
first_layer_acceleration = 800
infill_acceleration = 1000
max_print_speed = 150
perimeter_acceleration = 800

# Print parameters common to a 0.6mm diameter nozzle.

