[printer:Voron_Switchwire_afterburner volcano 1.2 nozzle]
inherits = *Voron_Switchwire_afterburner*; *1.2nozzle*; *volcano_afterburner*
printer_variant = volcano 1.2
printer_notes = VOLCANO
default_filament_profile = Basic PLA VOLCANO @VORON

# Common print preset, mostly derived from MK2 single material with a 0.4mm nozzle.
# All other print presets will derive from the *common* print preset.
