[printer_model:DQXL]
name = DeltiQ XL
variants = 0.4
technology = FFF
family = DeltiQ
default_materials = PLA @DQ;ASA @DQ;PET @DQ;ABS @DQ;CPE @DQ

# DeltiQ print styles #

thumbnail = DQXL_thumbnail.png
