[printer_model:HSP1-I Duplicator Mode]
name = HSP1-I Duplicator Mode
variants = 0.6; 0.4; 0.8; 1.0
technology = FFF
family = HSP1
bed_model = hsp1_i_duplicator_bed.stl
bed_texture = hsp1_i_duplicator.svg
default_materials = Layer Line Engineering PLA @HSP1; Push Plastic PETG @HSP1; Push Plastic PLA @HSP1;

# All presets starting with asterisk, for example *common*, are intermediate and they will
# not make it into the user interface.

#################### Common print presets ####################
thumbnail = HSP1-I Duplicator Mode_thumbnail.png
