[printer:MakerGear M3 Independent Dual Rev.1 0.75 Nozzle (Duplication Mode)]
inherits = MakerGear M3 Independent Dual Rev.1 (Duplication Mode)
default_print_profile = 0.25mm Quality @0.75 nozzle MakerGear
max_layer_height = 0.5
min_layer_height = 0.15
nozzle_diameter = 0.75
printer_variant = 0.75
retract_length = 1
retract_speed = 35

# -----------------------------------
# MakerGear Ultra One
# -----------------------------------
