[printer:MakerGear Micro]
inherits = *default*
bed_shape = 0x0, 81x0, 81x81, 0x81
default_filament_profile = "MakerGear PLA @MakerGear_Micro"
default_print_profile = 0.20mm Normal @0.40 Nozzle MakerGear
end_gcode = M104 S0 ; Turn off hotend temperature \nG1 X0 Y81 Z95
gcode_flavor = marlin
machine_max_acceleration_e = 2000, 2000
machine_max_acceleration_extruding = 2000, 2000
machine_max_acceleration_retracting = 2000, 2000
machine_max_acceleration_x = 450, 450
machine_max_acceleration_y = 450, 450
machine_max_acceleration_z = 10, 10
machine_max_feedrate_e = 30, 30
machine_max_feedrate_x = 300, 300
machine_max_feedrate_y = 300, 300
machine_max_feedrate_z = 20, 20
machine_max_jerk_e = 10, 10
# machine_max_jerk_x = Using Junction Deviation Factor
# machine_max_jerk_y = Using Junction Deviation Factor
# machine_max_jerk_z = Using Junction Deviation Factor
max_layer_height = 0.3
max_print_height = 100
nozzle_diameter = 0.40
printer_model = MAKERGEAR_MICRO
printer_notes = Dont remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_MAKERGEAR\nPRINTER_MODEL_MAKERGEAR_MICRO\n 
printer_variant = 0.40
retract_length = 6
retract_speed = 60
start_gcode = G90 ; blank \nM82 ; blank \nG28 ; home all axes \nG29 ; Mesh testing \nG1 X0 Y0 ; moves axes \nM109 S[first_layer_temperature_[current_extruder]] ; wait for hotend to reach first layer temperature
# thumbnails = 16x16, 261x256

# ---------------------------
# MakerGear M2
# ---------------------------
