[filament:*HS-PLA*]
inherits = *common*
filament_vendor = Geeetech
filament_colour = #F94D0C
filament_max_volumetric_speed = 0
filament_type = PLA
filament_density = 1.24
filament_cost = 20
first_layer_temperature = 210
temperature = 215
first_layer_bed_temperature = 60
bed_temperature = 60
cooling = 1
fan_always_on = 1
min_fan_speed = 100
bridge_fan_speed = 100
bridge_internal_fan_speed = -1
top_fan_speed = -1
external_perimeter_fan_speed = -1
support_material_interface_fan_speed = -1
disable_fan_first_layers = 1
full_fan_speed_layer = 0
fan_below_layer_time = 10
max_fan_speed = 100
slowdown_below_layer_time = 1
max_speed_reduction = 15
min_print_speed = 211
#"material_print_temperature": {"default_value": 210,"value":  "200 if speed_infill <=150 else 205 if speed_infill <= 200 else 215 if speed_infill <= 260 else 220","maximum_value": "250" },

