[filament:Speed PLA @Trimaker Nebula Cloud]
inherits = *PLA*
first_layer_temperature = 230
temperature = 230

filament_vendor = Generic

#//////////////////////////////////////////////#
#---------------# Nozzle sizes #---------------#
#//////////////////////////////////////////////#

