[print:*Soluble Support*]
inherits = *Soluble*
support_material_pattern = honeycomb
support_material_extruder = 2
support_material_interface_extruder = 2
support_material_with_sheath = 1

#################### Layer height presets ####################
