[printer_model:ULTIMAKERSline]
name = Ultimaker S-line
variants = 0.4
technology = FFF
bed_texture = ultimaker2.svg
default_materials = Generic PLA

# All presets starting with asterisk, for example *common*, are intermediate and they will
# not make it into the user interface.

# Common print preset
thumbnail = ULTIMAKERSline_thumbnail.png
