[printer_model:SV01 PRO]
name = SV01 PRO
variants = 0.4; 0.3; 0.6; 0.8
technology = FFF
family = SV
bed_model = SV01_bed.stl
bed_texture = SV03_texture.svg
default_materials = Generic PLA @SOVOL; Generic ABS @SOVOL; Generic PETG @SOVOL; Prusament ASA @SOVOL; Prusament PC Blend @SOVOL; Prusament PC Blend Carbon Fiber @SOVOL; Prusament PA11 Carbon Fiber @SOVOL

# All presets starting with asterisk, for example *common*, are intermediate and they will
# not make it into the user interface.

# Common print presets

thumbnail = SV01 PRO_thumbnail.png
