[print:0.10mm Fine @0.35 nozzle MakerGear]
inherits = *0.10mm*
bridge_speed = 40
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_MAKERGEAR.*/ and printer_notes=~/.*PRINTER_MODEL_MAKERGEAR_(U1|M(2|2_DUAL|3_SE|3_ID|3_ID_DUPLICATION)).*/ and nozzle_diameter[0]==0.35
external_perimeter_speed = 45
fill_density = 15%
fill_pattern = 3dhoneycomb
infill_acceleration = 1000
infill_speed = 55
max_print_speed = 200
perimeter_speed = 45
solid_infill_speed = 80
top_solid_infill_speed = 40

# ---------------------------
# 0.15mm
# ---------------------------
