[print:0.15mm Quality @0.40 nozzle MakerGear]
inherits = *0.15mm*; *0.40nozzle*
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_MAKERGEAR.*/ and printer_notes=~/.*PRINTER_MODEL_MAKERGEAR_MICRO.*/ and nozzle_diameter[0]==0.40
first_layer_height = 0.2

# ---------------------------
# 0.20mm
# ---------------------------
