[print:0.25mm Speed @0.35 nozzle MakerGear]
inherits = *0.25mm*
bridge_speed = 60
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_MAKERGEAR.*/ and printer_notes=~/.*PRINTER_MODEL_MAKERGEAR_(U1|M(2|2_DUAL|3_SE|3_ID|3_ID_DUPLICATION)).*/ and nozzle_diameter[0]==0.35
external_perimeter_speed = 70
infill_acceleration = 2000
infill_speed = 200
max_print_speed = 200
perimeter_speed = 75
solid_infill_speed = 200
top_solid_infill_speed = 70

# Micro
