[print:0.35mm Speed @0.75 nozzle MakerGear]
inherits = *0.35mm*; *0.75nozzle*
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_MAKERGEAR.*/ and printer_notes=~/.*PRINTER_MODEL_MAKERGEAR_(U1|M(2|2_DUAL|3_SE|3_ID|3_ID_DUPLICATION)).*/ and nozzle_diameter[0]==0.75

# ---------------------------
# 0.40mm (NOT READY)
# ---------------------------
