[print:*0.25nozzle*]
elefant_foot_compensation = 0
external_perimeter_extrusion_width = 0.30
extrusion_width = 0.30
first_layer_extrusion_width = 0.3
infill_extrusion_width = 0.30
output_filename_format = {input_filename_base}_{nozzle_diameter[0]}n_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
perimeter_extrusion_width = 0.30
solid_infill_extrusion_width = 0.30
support_material_extrusion_width = 0.30
support_material_interface_layers = 0
support_material_interface_spacing = 0.15
support_material_spacing = 1
support_material_xy_spacing = 150%
top_infill_extrusion_width = 0.30

 ; Only for the MakerGear Micro 
