[printer:SV01 PRO 0.8 nozzle]
inherits = SV01 PRO
nozzle_diameter = 0.8
max_layer_height = 0.6
min_layer_height = 0.2
printer_variant = 0.8
retract_length = 0.7
retract_speed = 40
deretract_speed = 23
retract_lift = 0.25
start_gcode = //M85 S180 ; For use with raspberry only, it kills the printer if it loses the USB connection and remains inactive for 3 minutes. It works in Marlin 1.1.6\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nG28 ; Home all axes\nG29 ; Auto bed-level (BL-Touch) // Comment if you don't like the automatic level in each print\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0 ; Reset Extruder\nG1 X5 Y20 Z2.0 F3000.0 ; Move to start position\nM109 S[first_layer_temperature] ; wait for extruder temp\nG1 X5 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line\nG1 X5 Y200.0 Z0.3 F5000.0 ; Move to side a little\nG1 X5.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line\nG92 E0 ; Reset Extruder\nG1 Z1.0 F3000 ; 
default_print_profile = 0.40mm QUALITY @0.8 nozzle SV01
default_filament_profile = Generic PLA 0.8 @SOVOL
color_change_gcode = M600\nG1 E0.6 F1500 ; prime after color change



# XXXXXXXXXXXXXXXXX
# XXX--- SV02 ---XXX
# XXXXXXXXXXXXXXXXX

