[filament:Layer Line DuraPET @HSP1 0.4 Takoto]
inherits = *Layer Line DuraPET*; *0.4 Takoto*
temperature = 285
bed_temperature = 80
first_layer_temperature = 280
first_layer_bed_temperature = 80
extrusion_multiplier = 1.00
filament_max_volumetric_speed = 12
min_fan_speed = 80  
max_fan_speed = 80
bridge_fan_speed = 80
start_filament_gcode = "; Filament gcode\n{local pressure_advance = 0.0}\n{if printer_notes=~/.*DUPLICATOR_MODE.*/}\nM572 D0:1 S{pressure_advance}\n{else}\nM572 D{current_extruder} S{pressure_advance}\n{endif}"

################### Layer Line 0.6 presets ###################
