[filament:Push Plastic PETG @HSP1 0.8 Takoto]
inherits = *Push Plastic PETG*; *0.8 Takoto*
temperature = 245
bed_temperature = 80
first_layer_temperature = 240
first_layer_bed_temperature = 80
extrusion_multiplier = 0.94
filament_max_volumetric_speed = 18
min_fan_speed = 80
max_fan_speed = 80
bridge_fan_speed = 80
start_filament_gcode = "; Filament gcode\n{local pressure_advance = 0.030}\n{if printer_notes=~/.*DUPLICATOR_MODE.*/}\nM572 D0:1 S{pressure_advance}\n{else}\nM572 D{current_extruder} S{pressure_advance}\n{endif}"

################## Push Plastic 1.0 presets ##################
