[print:0.28mm Draft @VORON2 - HF0.4mm]
inherits = *CORE_XY_DRAFT_0.28@HF0.4*; *V2_HF04*; *CORE_XY_SPEED*
overhang_speed_2 = 50
support_material_threshold = 35
external_perimeter_acceleration = 3000
perimeter_acceleration = 6000
support_material_spacing = 2.5
infill_speed = 300

# VORON2 - 0.5mm nozzle

