[print:0.40mm Strength @SWITCHWIRE - HF0.6mm]
inherits = 0.40mm Strength @VORON2 - HF0.6mm; *CORE_XZ_06*; *VSW_HF06*
default_acceleration = 2000
infill_acceleration = 3000
perimeter_acceleration = 2000
gap_fill_speed = 60
perimeter_speed = 80
overhang_speed_2 = 40

# VORON Switchwire - 0.8mm nozzle

