[print:*0.4nozzle*]
perimeters = 3
support_material_interface_spacing = 0.2
support_material_spacing = 1
first_layer_height = 0.2
extrusion_width = 0.44
external_perimeter_extrusion_width = 0.42
first_layer_extrusion_width = 0.56
infill_extrusion_width = 0.44
perimeter_extrusion_width = 0.44
solid_infill_extrusion_width = 0.44
top_infill_extrusion_width = 0.44
support_material_extrusion_width = 0.44

# Print parameters common to a 0.2mm diameter nozzle.
