[print:*CORE_XY_DRAFT_0.28@HF0.4*]
inherits = *common*
layer_height = 0.28
top_solid_layers = 4
bottom_solid_layers = 3
perimeter_speed = 200
external_perimeter_speed = 180
small_perimeter_speed = 180
solid_infill_speed = 200
first_layer_extrusion_width = 0.55
perimeter_extrusion_width = 0.55
external_perimeter_extrusion_width = 0.55
infill_extrusion_width = 0.55
solid_infill_extrusion_width = 0.55
top_infill_extrusion_width = 0.45
support_material_extrusion_width = 0.4
top_solid_infill_acceleration = 2000
support_material_contact_distance = 0.28
support_material_interface_layers = 3
over_bridge_speed = 50%
min_bead_width = 95%
default_acceleration = 3000
first_layer_speed = 45

# CoreXY - 0.5mm Nozzle

