[printer:Original Prusa MK3.5 & MK3.5S MMU3 0.6 nozzle]
inherits = Original Prusa MK3.5 & MK3.5S MMU3 0.4 nozzle; *MK3.5MMU3*
renamed_from = "Original Prusa MK3.5 MMU3 0.6 nozzle"
printer_model = MK3.5MMU3
printer_variant = 0.6
nozzle_diameter = 0.6,0.6,0.6,0.6,0.6
max_layer_height = 0.40,0.40,0.40,0.40,0.40
min_layer_height = 0.15,0.15,0.15,0.15,0.15
default_print_profile = 0.25mm SPEED @MK3.5 0.6

## COREONEL

