[printer:Original Prusa MK3.9 MMU3 HF0.4 nozzle]
inherits = Original Prusa MK3.9 MMU3 0.4 nozzle
printer_variant = HF0.4
multimaterial_purging = 240
printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\n\nPRINTER_MODEL_MK4IS\nMMU3\nPG\nHF_NOZZLE
default_print_profile = 0.20mm SPEED @MK4IS HF0.4
default_filament_profile = "Prusament PLA @HF0.4"
nozzle_high_flow = 1,1,1,1,1

; [printer:Original Prusa MK3.9 MMU3 HF0.6 nozzle]
; inherits = Original Prusa MK3.9 MMU3 0.6 nozzle
; printer_variant = HF0.6
; nozzle_high_flow = 1,1,1,1,1
; multimaterial_purging = 240
; default_print_profile = 0.25mm SPEED @MK4IS HF0.6
; default_filament_profile = "Prusament PLA @HF0.6"

