[printer_model:Q5]
name = FLSun Q5
variants = 0.4; 0.6
technology = FFF
bed_model = Q5_bed.stl
bed_texture = Q5.svg
default_materials = Generic PLA @FLSUN; Generic PETG @FLSUN; Generic ABS @FLSUN; Generic SPLA @FLSUN; Generic FLEX @FLSUN

#########################################
###### begin Common print presets #######
#########################################

# Common print preset
thumbnail = Q5_thumbnail.png
