[print:0.36mm Fine @X-Plus 3 0.6 nozzle]
inherits = *X-Plus 3*; *0.36mm Quick*
compatible_printers_condition = printer_model=="X-Plus 3" and nozzle_diameter[0]==0.6

# X-Plus 3 0.8 nozzle Print preset
