[print:0.24mm DRAFT @BIBO2]
inherits = *0.24mm*
# alias = 0.24mm DRAFT
travel_speed = 130
infill_speed = 50
solid_infill_speed = 40
top_solid_infill_speed = 30
support_material_extrusion_width = 0.38

