[printer:*proton_x_common*]
printer_vendor = INAT s.r.o.
default_filament_profile = "Generic PLA @PROTON_X"
#general
printer_technology = FFF
bed_shape = 0x0,304x0,304x304,0x304
max_print_height = 650
z_offset = 0
extruders_count = 1
gcode_flavor = marlin
silent_mode = 0
remaining_times = 1
use_relative_e_distances = 0
use_firmware_retraction = 0
use_volumetric_e = 0
variable_layer_height = 1
#gcodes
start_gcode = G28 ;Home\nG0 X-2 Y150 F6000 ;Move to the side\nG0 Z0.3 F200 ;Move nozzle down\nM192 ; Wait for probe temperature to settle\nG28 Z\nG29\nG0 X0 Y0 Z30 F6000\nM84 E\nM0\nG1 Z15.0 F6000 ;Move the platform down 15mm\n
end_gcode = M400\nM104 S0\nM140 S0\nM107\n;Retract the filament\nG92 E1\nG1 E-1 F300\nG28 X R5\nG0 Y300 F2000\nM84\n
color_change_gcode = M600
#limits
machine_limits_usage = emit_to_gcode
machine_max_feedrate_x = 200,200
machine_max_feedrate_y = 200,200
machine_max_feedrate_z = 10,10
machine_max_feedrate_e = 100,100
machine_max_acceleration_x = 500,500
machine_max_acceleration_y = 500,500
machine_max_acceleration_z = 200,200
machine_max_acceleration_e = 8000,8000
machine_max_acceleration_extruding = 1000,1000
machine_max_acceleration_retracting = 8000,8000
machine_max_jerk_x = 8,8
machine_max_jerk_y = 8,8
machine_max_jerk_z = 3,3
machine_max_jerk_e = 10,10
machine_min_extruding_rate = 5
#extruder 1
nozzle_diameter = 0.4
min_layer_height = 0.05
max_layer_height = 0.33
extruder_offset = 0x0
retract_length = 1.5
retract_lift = 0.6
retract_lift_above = 0
retract_lift_below = 0
retract_speed = 45
deretract_speed = 0
retract_restart_extra = 0
retract_before_travel = 2
retract_layer_change = 0
wipe = 1
retract_before_wipe = 100%
extruder_clearance_radius = 85
extruder_clearance_height = 34

