[printer_model:X-smart 3]
name = X-smart 3
variants = 0.4; 0.2; 0.6; 0.8
technology = FFF
family = X 3
bed_model = X-smart 3_bed.stl
bed_texture = X-smart 3.svg
default_materials = QIDI ABS Odorless @X-smart 3 0.4 nozzle;QIDI ABS Rapido @X-smart 3 0.4 nozzle; QIDI PLA Rapido @X-smart 3 0.4 nozzle; QIDI PLA Rapido Matte @X-smart 3 0.4 nozzle; QIDI PLA-CF @X-smart 3 0.4 nozzle; Generic ABS @X-smart 3 0.4 nozzle; Generic PLA @X-smart 3 0.4 nozzle

# All presets starting with asterisk, for example *common*, are intermediate and they will
# not make it into the user interface.

# Common print presets
thumbnail = X-smart 3_thumbnail.png
