[filament:QIDI PLA Rapido Matte @Q1 Pro 0.2 nozzle]
inherits = *QIDI PLA Rapido Matte*
start_filament_gcode = "; Filament gcode\nM900 K0.042 T0.03\n"
filament_max_volumetric_speed = 2
temperature = 210
compatible_printers_condition = printer_model=="Q1 Pro" and nozzle_diameter[0]==0.2

# Q1 Pro 0.2 nozzle Generic filament preset
