[printer_model:BIQUBX]
name = BIQU BX
variants = 0.4
technology = FFF
bed_model = BX_Bed.stl
bed_texture = BX_Texture.png
default_materials = Generic PLA @BIQU; Generic PETG @BIQU; Generic ABS @BIQU

# All presets starting with asterisk, for example *common*, are intermediate and they will
# not make it into the user interface.

# Common print preset
thumbnail = BIQUBX_thumbnail.png
