[print:0.07mm DETAIL @MK4IS 0.25]
inherits = *MK4IS_common025*
layer_height = 0.07
bottom_solid_layers = 9
top_solid_layers = 11
support_material_contact_distance = 0.11
raft_contact_distance = 0.1
perimeter_speed = 60
small_perimeter_speed = 40
external_perimeter_speed = 40
top_solid_infill_speed = 60
gap_fill_speed = 40
support_material_speed = 60
external_perimeter_acceleration = 800
perimeter_acceleration = 1200
top_solid_infill_acceleration = 1000
solid_infill_acceleration = 2000
infill_acceleration = 2500
bridge_acceleration = 1000
default_acceleration = 1500
perimeter_extrusion_width = 0.25
external_perimeter_extrusion_width = 0.25
infill_extrusion_width = 0.25
solid_infill_extrusion_width = 0.25
solid_infill_speed = 140
bridge_speed = 30

; [print:0.10mm @MK4IS 0.25]
; inherits = 0.07mm @MK4IS 0.25
; layer_height = 0.1
; bottom_solid_layers = 8
; top_solid_layers = 10
; perimeter_speed = 70
; external_perimeter_acceleration = 1000
; perimeter_acceleration = 1500
; default_acceleration = 2000
; perimeter_extrusion_width = 0.27
; external_perimeter_extrusion_width = 0.27
; infill_extrusion_width = 0.27
; solid_infill_extrusion_width = 0.27
; support_material_contact_distance = 0.08
; raft_contact_distance = 0.07

