[print:0.20mm STRUCTURAL @COREONEL 0.3]
inherits = 0.20mm STRUCTURAL @MK4S 0.3; *C1L_03*
infill_acceleration = 6000
perimeter_speed = 70
external_perimeter_speed = 50
small_perimeter_speed = 50

# COREONE L 0.5mm nozzle

