[print:0.30mm DRAFT @MK4 0.4]
inherits = *0.30mm*; *MK4*
bottom_solid_layers = 3
perimeter_speed = 70
external_perimeter_speed = 40
small_perimeter_speed = 40
infill_speed = 95
solid_infill_speed = 85
top_solid_infill_speed = 40
support_material_contact_distance = 0.2
raft_contact_distance = 0.2
support_material_style = snug
support_material_interface_layers = 3
support_material_speed =  60
support_material_interface_speed = 70%
support_material_xy_spacing = 80%
gap_fill_speed = 45
bridge_speed = 25
external_perimeter_acceleration = 1000
perimeter_acceleration = 1100
top_solid_infill_acceleration = 800
solid_infill_acceleration = 1700
infill_acceleration = 2000
bridge_acceleration = 1000
first_layer_acceleration = 600
default_acceleration = 1000
max_print_speed = 200
external_perimeter_extrusion_width = 0.5
extrusion_width = 0.5
first_layer_extrusion_width = 0.5
infill_extrusion_width = 0.5
perimeter_extrusion_width = 0.5
solid_infill_extrusion_width = 0.5
top_infill_extrusion_width = 0.45
support_material_extrusion_width = 0.38
compatible_printers_condition = printer_model=="MK4" and nozzle_diameter[0]==0.4

## MK4 - 0.5mm nozzle

