[print:0.55mm STRUCTURAL @MK4IS HF0.8]
inherits = 0.55mm DRAFT @MK4IS 0.8
perimeter_speed = 75
external_perimeter_speed = 45
small_perimeter_speed = 45
infill_speed = 75
solid_infill_speed = 65
gap_fill_speed = 60
top_solid_infill_acceleration = 1200
top_solid_infill_speed = 45
support_material_speed = 65
compatible_printers_condition = printer_notes=~/.*MK4IS.*/ and nozzle_diameter[0]==0.8 and nozzle_high_flow[0]

## MK4S

# MK4S common

