[print:*C1_Shared08*]
inherits = *C1*
first_layer_infill_speed = 55
compatible_printers_condition = printer_model=~/(COREONE|COREONEMMU3)/ and nozzle_diameter[0]==0.8
solid_infill_acceleration = 4000
infill_acceleration = 6000

# COREONE 0.4mm nozzle

