[printer_model:COREONEL]
name = Prusa CORE One L
variants = HF0.4; HF0.5; HF0.6; HF0.8; 0.25; 0.3; 0.4; 0.5; 0.6; 0.8
technology = FFF
family = CORE
bed_model = coreonel_bed.stl
bed_texture = coreonel.svg
thumbnail = COREONEL_thumbnail.png
default_materials = Prusament PLA @COREONE HF0.4; Prusament PLA Blend @COREONE; Prusament PETG @COREONE HF0.4; Generic PLA @COREONE HF0.4; Prusament ASA @COREONE HF0.4; Prusament PC Blend @COREONE HF0.4; Generic PETG @COREONE HF0.4; Generic PLA Silk @COREONE

; [printer_model:COREONELMMU3]
; name = Prusa CORE One L MMU3
; variants = 0.4; 0.6; HF0.4
; technology = FFF
; family = CORE
; bed_model = coreonel_bed.stl
; bed_texture = coreonel.svg
; thumbnail = COREONELMMU3_thumbnail.png
; default_materials = Prusament PLA @COREONE; Prusament PLA Blend @COREONE; Prusament PETG @COREONE; Generic PLA @COREONE; Prusament ASA @COREONE; Prusament PC Blend @COREONE; Generic PETG @COREONE; Generic PLA Silk @COREONE

