[printer:*common_CaribouIDEX_printer*]
autoemit_temperature_commands = 0
bed_custom_model =
bed_custom_texture =
bed_shape = 0x0,250x0,250x210,0x210
before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
between_objects_gcode =
binary_gcode = 0
color_change_gcode = M600
cooling_tube_length = 5
cooling_tube_retraction = 91.5
default_filament_profile = "Caribou PLA @Caribou"
default_print_profile = 0.20mm QUALITY @Caribou
deretract_speed = 0,0
end_gcode = G4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\n
extra_loading_move = -2
extruder_colour = #02F010;#02F010
extruder_offset = 0x0,0x0
extruder_clearance_height = 20
extruder_clearance_radius = 45
gcode_flavor = reprapfirmware
high_current_on_filament_swap = 0
host_type = duet
inherits =
layer_gcode = {if layer_num == 1}\n   M221 D0 S100\n   M221 D1 S100\n   {if is_extruder_used[0]}\n      M568 P0 S{temperature[0]} R{temperature[0]+ standby_temperature_delta}\n   {endif}\n   {if is_extruder_used[1]}\n      M568 P1 S{temperature[1]} R{temperature[1]+ standby_temperature_delta}\n   {endif}\n{endif}
machine_limits_usage = time_estimate_only
machine_max_acceleration_e = 5000,5000
machine_max_acceleration_extruding = 1250,1250
machine_max_acceleration_retracting = 1250,1250
machine_max_acceleration_travel = 1500,1250
machine_max_acceleration_x = 1000,960
machine_max_acceleration_y = 1000,960
machine_max_acceleration_z = 200,200
machine_max_feedrate_e = 120,120
machine_max_feedrate_x = 200,100
machine_max_feedrate_y = 200,100
machine_max_feedrate_z = 12,12
machine_max_jerk_e = 4.5,4.5
machine_max_jerk_x = 8,8
machine_max_jerk_y = 8,8
machine_max_jerk_z = 0.4,0.4
machine_min_extruding_rate = 0,0
machine_min_travel_rate = 0,0
max_layer_height = 0.3,0.3
max_print_height = 217
min_layer_height = 0.05,0.05
multimaterial_purging = 140
nozzle_diameter = 0.4,0.4
parking_pos_retraction = 92
pause_print_gcode = M601
print_host =
printer_model = Caribou_IDEX_Standard
printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CARIBOU3D\nPRINTER_MODEL_DUET\n
printer_settings_id =
printer_technology = FFF
printer_variant = 0.4
printer_vendor =
printhost_apikey =
printhost_cafile =
remaining_times = 1
retract_before_travel = 1,1
retract_before_wipe = 0%,0%
retract_layer_change = 1,1
retract_length = 0.4,0.4
retract_length_toolchange = 4,4
retract_lift = 0.4,0.4
retract_lift_above = 0,0
retract_lift_below = 216,216
retract_restart_extra = 0,0
retract_restart_extra_toolchange = 0,0
retract_speed = 25,25
silent_mode = 1
single_extruder_multi_material = 0
start_gcode = T-1 P0                          ; deselect tools\nG0 X60 Y-5 Z80                  ; move extruder 0 above bed\n;\nM568 P0 S{first_layer_temperature[0]} R{160} A1\n;\n{if is_extruder_used[1]}\n   M568 P1 S{first_layer_temperature[1]} R{160} A1\n{else}\n   M568 P1 S0 R0 A0            ; if extruder 1 is not used we can turn heating off\n{endif}\n;\nM140 S[first_layer_bed_temperature] ; set bed temerature\nM190 S[first_layer_bed_temperature] ; wait for bed temperature\nM116 P0                             ; wait for tool 0 temperature\n;\nG29                            ; mesh bed leveling using defined mesh grid\nG90                            ; absolute positioning\n;\n{if is_extruder_used[1]}\n   G0 X-125 Y-5                ; park tool 0\n{else}\n   G0 X0 Y-5 Z0.6              ; move extruder near bed\n{endif}\n;\n{if is_extruder_used[0]}\n   M568 P0 S{first_layer_temperature[0]} R{first_layer_temperature[0]+ standby_temperature_delta} A2\n   M116 P0                     ; wait for tool 0 temperature\n   T0 P0                       ; select tool 0\n   M116 P0                     ; wait for temperature of extruder 0\n   M98 P"0:/sys/primeLine-X.g" ; execute primeline macro for x\n   {if is_extruder_used[1]}    ; move to parking position when tool 1 is used as well\n      G1 X-125 Z5              ; move tool 0 to parking position\n   {endif}\n{else}\n   M568 P0 S0 R0 A0            ; if extruder 0 is not used we can turn heating off\n{endif}\n;\n{if is_extruder_used[1]}\n   M568 P1 S{first_layer_temperature[1]} R{first_layer_temperature[1]+ standby_temperature_delta} A2\n   M116 P1                     ; wait for tool 1 temperature\n   T1 P1                       ; select tool 1\n   G0 X252 Y-5 Z0.6            ; move extruder near bed\n   M116 P1                     ; wait for temperature of extruder 1\n   M98 P"0:/sys/primeLine-U.g" ; execute primeline macro macro for u\n   {if initial_extruder != 1}\n      G1 U365 Z5                  ; move tool 1 to parking position\n   {endif}\n{endif}\n;\nT[initial_extruder]\n\n
template_custom_gcode =
thumbnails = 160x160/QOI, 450x450/QOI
thumbnails_format = QOI
toolchange_gcode =
travel_lift_before_obstacle = 0,0
travel_max_lift = 0,0
travel_ramping_lift = 0,0
travel_slope = 0,0
use_firmware_retraction = 0
use_relative_e_distances = 1
use_volumetric_e = 0
variable_layer_height = 1
wipe = 1,1
z_offset = 0

#---------------------------------------------------------------------------------------------------------------------------

