[printer:Caribou IDEX Standard 0.25 nozzle]
inherits = *common_CaribouIDEX_printer*
printer_model = Caribou_IDEX_Standard
printer_variant = 0.25
nozzle_diameter = 0.25,0.25
default_print_profile = 0.10mm QUALITY 0.25mm nozzle @Caribou

#---------------------------------------------------------------------------------------------------------------------------

