[filament:E3D PC-ABS @MakerGear]
inherits = *ABS*
filament_vendor = E3D
filament_cost = 0
filament_type = PC
filament_density = 1.05
first_layer_temperature = 275
temperature = 270

# ---------------------------
# ASA Filament
# ---------------------------
