[filament:3D-Fuel PET-CF @HF0.6]
inherits = 3D-Fuel PET-CF @PG 0.6; *PET06HF*
filament_max_volumetric_speed = 10

; [filament:3D-Fuel PET-CF @MK4S HF0.4]
; inherits = 3D-Fuel PET-CF @HF0.4; *PETHF4S*

