[filament:3DJAKE ecoPLA @COREONE HF0.8]
inherits = 3DJAKE ecoPLA @HF0.8; *PLA08HFC1*

; [filament:*Creality Hyper PLA*]
; inherits = *PLA*
; filament_vendor = Creality
; filament_cost = 18
; filament_density = 1.25
; filament_spool_weight = 160
; first_layer_temperature = 220
; temperature = 220
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.023{else}0.03{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K11{elsif nozzle_diameter[0]==0.8};{else}M900 K18{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.1{elsif nozzle_diameter[0]==0.8}0.07{elsif nozzle_diameter[0]==0.4}0.16{elsif nozzle_diameter[0]==0.25}0.49{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.021{elsif nozzle_diameter[0]==0.5}0.015{elsif nozzle_diameter[0]==0.6}0.012{elsif nozzle_diameter[0]==0.8}0.009{elsif nozzle_diameter[0]==0.25}0.07{elsif nozzle_diameter[0]==0.3}0.046{else}0{endif} ; Filament gcode\n{endif}"

; [filament:*PA_Creality_HyperPLA*]
; start_filament_gcode = "{if printer_notes!~/.*(MK4IS|XLIS|MK4S|MK3.9S|COREONE).*/}\nM900 K{if nozzle_diameter[filament_extruder_id]==0.4}0.03{elsif nozzle_diameter[filament_extruder_id]==0.25}0.078{elsif nozzle_diameter[filament_extruder_id]==0.3}0.04{elsif nozzle_diameter[filament_extruder_id]==0.6}0.017{elsif nozzle_diameter[filament_extruder_id]==0.5}0.02{elsif nozzle_diameter[filament_extruder_id]==0.8}0.009{else}0{endif} ; Legacy LA\n{else}\nM572 S{if nozzle_diameter[filament_extruder_id]==0.4}0.023{elsif nozzle_diameter[filament_extruder_id]==0.5}0.016{elsif nozzle_diameter[filament_extruder_id]==0.6}0.013{elsif nozzle_diameter[filament_extruder_id]==0.8}0.01{elsif nozzle_diameter[filament_extruder_id]==0.25}0.075{elsif nozzle_diameter[filament_extruder_id]==0.3}0.05{else}0{endif} ; Pressure advance\n{endif}\n\nM142 S36 ; set heatbreak target temp"

; [filament:*PAHF_Creality_HyperPLA*]
; start_filament_gcode = "M572 S{if nozzle_diameter[filament_extruder_id]==0.4}0.023{elsif nozzle_diameter[filament_extruder_id]==0.5}0.016{elsif nozzle_diameter[filament_extruder_id]==0.6}0.013{elsif nozzle_diameter[filament_extruder_id]==0.8}0.01{elsif nozzle_diameter[filament_extruder_id]==0.25}0.075{elsif nozzle_diameter[filament_extruder_id]==0.3}0.05{else}0{endif} ; Filament gcode\n\nM142 S36 ; set heatbreak target temp"

; [filament:Creality Hyper PLA @PG]
; inherits = *Creality Hyper PLA*; *PLAPG*; *PLAIS*; *PA_Creality_HyperPLA*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; filament_max_volumetric_speed = 17
; temperature = 220
; slowdown_below_layer_time = 6

; [filament:Creality Hyper PLA @PG 0.6]
; inherits = Creality Hyper PLA @PG; *PLA06PG*; *PLAIS*; *PA_Creality_HyperPLA*
; filament_max_volumetric_speed = 18
; temperature = 220

; [filament:Creality Hyper PLA @PG 0.8]
; inherits = Creality Hyper PLA @PG; *PLA08PG*; *PLAIS*; *PA_Creality_HyperPLA*
; filament_max_volumetric_speed = 20
; temperature = 225

; [filament:Creality Hyper PLA @MK4S]
; inherits = Creality Hyper PLA @PG; *PLAPG4S*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; slowdown_below_layer_time = 4

; [filament:Creality Hyper PLA @MK4S 0.6]
; inherits = Creality Hyper PLA @PG 0.6; *PLA06PG4S*

; [filament:Creality Hyper PLA @MK4S 0.8]
; inherits = Creality Hyper PLA @PG 0.8; *PLA08PG4S*

; [filament:Creality Hyper PLA @XL]
; inherits = Creality Hyper PLA @PG; *PLAXL*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; slowdown_below_layer_time = 7

; [filament:Creality Hyper PLA @XL 0.6]
; inherits = Creality Hyper PLA @PG 0.6; *PLA06XL*

; [filament:Creality Hyper PLA @XL 0.8]
; inherits = Creality Hyper PLA @PG 0.8; *PLA08XL*

; [filament:Creality Hyper PLA @HF0.4]
; inherits = Creality Hyper PLA @PG; *PLAHF*; *PAHF_Creality_HyperPLA*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; filament_max_volumetric_speed = 26

; [filament:Creality Hyper PLA @HF0.5]
; inherits = Creality Hyper PLA @HF0.4; *PLA05HF*; *PAHF_Creality_HyperPLA*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; filament_max_volumetric_speed = 27

; [filament:Creality Hyper PLA @HF0.6]
; inherits = Creality Hyper PLA @PG 0.6; *PLA06HF*; *PAHF_Creality_HyperPLA*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; filament_max_volumetric_speed = 32

; [filament:Creality Hyper PLA @HF0.8]
; inherits = Creality Hyper PLA @PG 0.8; *PLA08HF*; *PAHF_Creality_HyperPLA*
; filament_max_volumetric_speed = 37

; [filament:Creality Hyper PLA @MK4S HF0.4]
; inherits = Creality Hyper PLA @HF0.4; *PLAHF4S*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; slowdown_below_layer_time = 4

; [filament:Creality Hyper PLA @MK4S HF0.5]
; inherits = Creality Hyper PLA @HF0.5; *PLA05HF4S*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @MK4S HF0.6]
; inherits = Creality Hyper PLA @HF0.6; *PLA06HF4S*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @MK4S HF0.8]
; inherits = Creality Hyper PLA @HF0.8; *PLA08HF4S*

; [filament:Creality Hyper PLA @XL HF0.4]
; inherits = Creality Hyper PLA @PG; *PLAHFXL*; *PAHF_Creality_HyperPLA*
; filament_max_volumetric_speed = 26
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @XL HF0.5]
; inherits = Creality Hyper PLA @PG 0.6; *PLA05HFXL*; *PAHF_Creality_HyperPLA*
; filament_max_volumetric_speed = 27
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @XL HF0.6]
; inherits = Creality Hyper PLA @PG 0.6; *PLA06HFXL*; *PAHF_Creality_HyperPLA*
; filament_max_volumetric_speed = 32
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @XL HF0.8]
; inherits = Creality Hyper PLA @PG 0.8; *PLA08HFXL*; *PAHF_Creality_HyperPLA*
; filament_max_volumetric_speed = 37
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @COREONE]
; inherits = Creality Hyper PLA @PG; *PLAPGC1*; *PA_Creality_HyperPLA*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; slowdown_below_layer_time = 6

; [filament:Creality Hyper PLA @COREONE 0.6]
; inherits = Creality Hyper PLA @PG 0.6; *PLA06PGC1*

; [filament:Creality Hyper PLA @COREONE 0.8]
; inherits = Creality Hyper PLA @PG 0.8; *PLA08PGC1*

; [filament:Creality Hyper PLA @COREONE HF0.4]
; inherits = Creality Hyper PLA @HF0.4; *PLAHFC1*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0
; slowdown_below_layer_time = 6

; [filament:Creality Hyper PLA @COREONE HF0.5]
; inherits = Creality Hyper PLA @HF0.5; *PLA05HFC1*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @COREONE HF0.6]
; inherits = Creality Hyper PLA @HF0.6; *PLA06HFC1*
; filament_infill_max_speed = 0
; filament_infill_max_crossing_speed = 0

; [filament:Creality Hyper PLA @COREONE HF0.8]
; inherits = Creality Hyper PLA @HF0.8; *PLA08HFC1*

