[filament:*3D-Fuel PET-CF*]
inherits = *PET*
extrusion_multiplier = 1.03
filament_vendor = 3D-Fuel
first_layer_temperature = 285
temperature = 285
first_layer_bed_temperature = 90
bed_temperature = 90
filament_cost = 29.95
filament_density = 1.23
filament_type = PET
full_fan_speed_layer = 3
enable_dynamic_fan_speeds = 1
min_fan_speed = 10
max_fan_speed = 20
bridge_fan_speed = 30
fan_always_on = 0
fan_below_layer_time = 20
overhang_fan_speed_0 = 30
overhang_fan_speed_1 = 20
overhang_fan_speed_2 = 0
overhang_fan_speed_3 = 0
filament_max_volumetric_speed = 10
filament_abrasive = 1

; [filament:3D-Fuel PET-CF @PG]
; inherits = *3D-Fuel PET-CF*; *PETPG*
; filament_max_volumetric_speed = 6

