[filament:*ABS08HF4S*]
min_fan_speed = 15
max_fan_speed = 15
bridge_fan_speed = 20
compatible_printers_condition = printer_model=~/(MK4S|MK4SMMU3|MK3.9S|MK3.9SMMU3)/ and nozzle_diameter[0]==0.8 and nozzle_high_flow[0] and ! single_extruder_multi_material

# HF XL

