[filament:*PA08HF*]
inherits = *PA08PG*
filament_max_volumetric_speed = 20
compatible_printers_condition = printer_model=~/(MK4|MK4IS|MK4ISMMU3|MK3.9|MK3.9MMU3)/ and nozzle_diameter[0]==0.8 and nozzle_high_flow[0] and ! single_extruder_multi_material

# HF MK4S

