[filament:*PETHF4S*]
min_fan_speed = 20
max_fan_speed = 40
bridge_fan_speed = 40
fan_below_layer_time = 20
slowdown_below_layer_time = 7
compatible_printers_condition = printer_model=~/(MK4S|MK4SMMU3|MK3.9S|MK3.9SMMU3)/ and nozzle_diameter[0]!=0.8 and nozzle_diameter[0]!=0.6 and nozzle_diameter[0]!=0.5 and nozzle_high_flow[0]
enable_dynamic_fan_speeds = 1
overhang_fan_speed_0 = 40

#MMU3 parameters

filament_ramming_parameters = "250 100 42.4194 42.4194| 0.05 42.4387 0.45 42.4387 0.95 42.4387 1.45 42.4387 1.95 42.4387 2.45 42.4387 2.95 42.4387 3.45 42.4387 3.95 42.4387 4.45 42.4387 4.95 42.4387"

