[filament:*PLAHF4S*]
compatible_printers_condition = printer_model=~/(MK4S|MK4SMMU3|MK3.9S|MK3.9SMMU3)/ and nozzle_diameter[0]!=0.8 and nozzle_diameter[0]!=0.6 and nozzle_diameter[0]!=0.5 and nozzle_high_flow[0]
min_fan_speed = 70
max_fan_speed = 100
bridge_fan_speed = 100
fan_below_layer_time = 17
slowdown_below_layer_time = 6
min_print_speed = 20
enable_dynamic_fan_speeds = 1
overhang_fan_speed_0 = 100
overhang_fan_speed_1 = 100

# MMU3 parameters
filament_ramming_parameters = "250 100 39.871 39.871| 0.05 39.9547 0.45 39.9547 0.95 39.9547 1.45 39.9547 1.95 39.9547 2.45 39.9547 2.95 39.9547 3.45 39.9547 3.95 39.9547 4.45 39.9547 4.95 39.9547"

