[filament:Prusament PETG Carbon Fiber @MINI]
inherits = Prusament PETG @MINI
first_layer_temperature = 260
temperature = 265
bed_temperature = 85
extrusion_multiplier = 1.03
filament_cost = 54.99
filament_colour = #BBBBBB
compatible_printers_condition = printer_notes=~/.*MINI.*/ and nozzle_diameter[0]>=0.4 and nozzle_diameter[0]!=0.8 and nozzle_diameter[0]!=0.6

## [filament:Prusament PETG Tungsten 75% @MINI]
## inherits = Prusament PETG Tungsten 75%; *PETMINI*
## full_fan_speed_layer = 5
## start_filament_gcode = "M900 K0"
## filament_colour = #BBBBBB
## compatible_printers_condition = nozzle_diameter[0]>=0.4 and printer_notes=~/.*MINI.*/

