[filament:Prusament PETG Magnetite 40% @COREONE 0.8]
inherits = Prusament PETG Magnetite 40% @MK4S 0.8; *PET08PGC1*; *PG_NOHF08C1*
fan_below_layer_time = 20
fan_always_on = 0
min_fan_speed = 10
max_fan_speed = 20
bridge_fan_speed = 20

## [filament:Prusament PETG Tungsten 75%]
## inherits = *PET*
## filament_vendor = Prusa Polymers
## filament_colour = #BBBBBB
## first_layer_temperature = 255
## temperature = 265
## filament_cost = 277.09
## filament_density = 4
## filament_spool_weight = 278
## filament_type = PETG
## compatible_printers_condition = nozzle_diameter[0]>=0.4 and printer_model!="MK2SMM" and printer_notes!~/.*MINI.*/ and printer_notes!~/.*PG.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)
## cooling = 0
## min_fan_speed = 50
## max_fan_speed = 70
## start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.4}0.01{else}0{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif nozzle_diameter[0]==0.4}M900 K12{else}M900 K0{endif} ; Filament gcode LA 1.0"

## [filament:Prusament PETG Tungsten 75% @PG]
## inherits = Prusament PETG Tungsten 75%; *PETPG*
## filament_max_volumetric_speed = 8
## start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.4}0.01{else}0{endif} ; Filament gcode"

## [filament:Prusament PETG Tungsten 75% @PG 0.6]
## inherits = Prusament PETG Tungsten 75% @PG; *PET06PG*
## filament_max_volumetric_speed = 9

## [filament:Prusament PETG Tungsten 75% @PG 0.8]
## inherits = Prusament PETG Tungsten 75% @PG; *PET08PG*
## filament_max_volumetric_speed = 10

