[filament:SemiFlex]
## discontinued
inherits = *FLEX*
renamed_from = "SemiFlex or Flexfill 98A"
filament_vendor = Generic
filament_cost = 82.26
filament_density = 1.22
extrusion_multiplier = 1.12
filament_max_volumetric_speed = 1.35
fan_always_on = 1
cooling = 0
max_fan_speed = 30
min_fan_speed = 30
filament_retract_length = nil

