[printer:*common*]
printer_technology = FFF
autoemit_temperature_commands = 0
color_change_gcode = M600
gcode_flavor = reprapfirmware
high_current_on_filament_swap = 0
machine_limits_usage = time_estimate_only
machine_max_acceleration_e = 2400
machine_max_acceleration_extruding = 5000
machine_max_acceleration_retracting = 5000
machine_max_acceleration_travel = 5000
machine_max_acceleration_x = 5000
machine_max_acceleration_y = 5000
machine_max_acceleration_z = 300
machine_max_feedrate_e = 100
machine_max_feedrate_x = 500
machine_max_feedrate_y = 500
machine_max_feedrate_z = 10
machine_max_jerk_e = 15
machine_max_jerk_x = 4
machine_max_jerk_y = 4
machine_max_jerk_z = 2.5
max_print_height = 1000
parking_pos_retraction = 92
pause_print_gcode = M226
remaining_times = 1
silent_mode = 0
single_extruder_multi_material = 0
thumbnails = 256x256/QOI
use_firmware_retraction = 0
use_relative_e_distances = 1
use_volumetric_e = 0
variable_layer_height = 1
z_offset = 0
extruder_clearance_height = 90
extruder_clearance_radius = 95
default_filament_profile = Layer Line Engineering PLA @HSP1
end_gcode = ; Stop the print\nM0\n\n;NUM_LAYERS:[total_layer_count]\n
before_layer_gcode = ;LAYER:[layer_num]

# dual preset
