[printer:*dual*]
inherits = *common*
printer_model = HSP1-I
autoemit_temperature_commands = 0
bed_shape = 0x0,650x0,650x640,0x640
extruder_colour = #FFFF00;#FF00FF
extruder_offset = 0x0,0x0
wipe = 1,1
retract_before_wipe = 50%,50%
retract_layer_change = 1,1
retract_length_toolchange = 2,2
retract_lift = 0.4,0.4
retract_lift_above = 0,0
retract_lift_below = 0,0
retract_restart_extra = 0,0
retract_restart_extra_toolchange = 0,0
retract_speed = 35,35
deretract_speed = 0,0
toolchange_gcode = T{next_extruder}\nM116 P{next_extruder} S5
layer_gcode = {if layer_num == 1}M140 S{max((is_extruder_used[0]? bed_temperature[0]:0),(is_extruder_used[1]? bed_temperature[1]:0))}{endif}
printer_notes = ;Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_HSP\nPRINTER_MODEL_HSP1-I\n
start_gcode = ; Run nozzle diameter and filament check\nM98 P{"{directories.system^\\"/System Macros/Config Checks/nozzle_check.g\\"}"} {if is_extruder_used[0]}L{nozzle_diameter[0]}{endif} {if is_extruder_used[1]}S{nozzle_diameter[1]}{endif}\nM98 P{"{directories.system^\\"/System Macros/Config Checks/filament_check.g\\"}"} {if is_extruder_used[0]}{if filament_notes[0] == ""}L"{filament_type[0]}"{else}A"{filament_notes[0]}"{endif}{endif} {if is_extruder_used[1]}{if filament_notes[1] == ""}S"{filament_type[1]}"{else}B"{filament_notes[1]}"{endif}{endif}\n\n; set extruder temp\n{if is_extruder_used[0]}M568 P0 S{first_layer_temperature[0]} R{(!is_nil(idle_temperature[0])? idle_temperature[0]:first_layer_temperature[0]-60)} A1{endif}\n{if is_extruder_used[1]}M568 P1 S{first_layer_temperature[1]} R{(!is_nil(idle_temperature[1])? idle_temperature[1]:first_layer_temperature[1]-60)} A1{endif}\n\n; Set and wait for bed temp\nM190 S{max((is_extruder_used[0]? first_layer_bed_temperature[0]:0),(is_extruder_used[1]? first_layer_bed_temperature[1]:0))}\n\n; Home all axes\nG28\n\n; Enable mesh compensation\nM98 P{"{directories.system^\\"/System Macros/Config Checks/load_heightmap.g\\"}"}\n\n; Move to starting position\nG0 H2 X{"{move.axes[0].min}"} Y50 F6000\n\n; Select first tool\nT{initial_extruder}\n\n; Move near start\nG1 X[first_layer_print_min_0] Y[first_layer_print_min_1] Z{first_layer_height + 2.0} F12000\n

# duplicator preset
