[printer:*duplicator*]
inherits = *common*
printer_model = HSP1-I Duplicator Mode
autoemit_temperature_commands = 0
bed_shape = 0x0,320x0,320x640,0x640 
extruder_colour = #FFFF00
extruder_offset = 0x0
wipe = 1
retract_before_wipe = 50%
retract_layer_change = 1
retract_length_toolchange = 0
retract_lift = 0.4
retract_lift_above = 0
retract_lift_below = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 35
deretract_speed = 0
printer_notes = ;Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_HSP\nPRINTER_MODEL_HSP1-I\nDUPLICATOR_MODE\n
start_gcode = ; Run nozzle diameter and filament check\nM98 P{"{directories.system^\\"/System Macros/Config Checks/nozzle_check.g\\"}"} L{nozzle_diameter[0]} S{nozzle_diameter[0]}\nM98 P{"{directories.system^\\"/System Macros/Config Checks/filament_check.g\\"}"} {if filament_notes[0] == ""}L"{filament_type[0]}" S"{filament_type[0]}"{else}A"{filament_notes[0]}" B"{filament_notes[0]}"{endif}\n\n; set extruder temp\nM568 P2 S{first_layer_temperature[0]} R{(!is_nil(idle_temperature[0])? idle_temperature[0]:first_layer_temperature[0]-60)} A1\n\n; Set and wait for bed temp\nM190 S{first_layer_bed_temperature[0]}\n\n; Home all axes\nG28\n\n; Enable mesh compensation\nG29 S1\n\n; Move to starting position\nG0 H2 X{"{move.axes[0].min}"} Y50 F6000\n\n; Select duplicator "tool"\nT2\n\n; Move near start\nG1 X[first_layer_print_min_0] Y[first_layer_print_min_1] Z{first_layer_height + 2.0} F12000\n

# mirror preset
