[printer:HSP1-I - 2x1.0mm Takoto]
inherits = *dual*; *1.0*
nozzle_diameter = 1.0,1.0
retract_length = 1,1
default_print_profile = 500 Micron Standard @HSP1


################# Duplicator printer presets #################
