[printer:*spriteextruder*]
retract_length = 0.6
retract_speed = 40
deretract_speed = 40
retract_before_travel = 1
retract_before_wipe = 0%

# Intended for printers with dual extruders and a single hotend/nozzle, like the CR-X series
