[printer:*M1_SpeedPrinter*]
# Presets for M1 printers
inherits = *common*
machine_max_feedrate_x = 300
machine_max_feedrate_y = 300
machine_max_feedrate_z = 25
machine_max_feedrate_e = 60
machine_max_acceleration_x = 3000
machine_max_acceleration_y = 3000
machine_max_acceleration_z = 500
machine_max_acceleration_e = 5000
machine_max_acceleration_extruding = 3500
machine_max_acceleration_retracting = 3500
machine_max_jerk_x = 10
machine_max_jerk_y = 10
machine_max_jerk_z = 3
machine_max_jerk_e = 10	
machine_min_extruding_rate = 0
machine_min_travel_rate = 5
extruder_colour = #F5DC1E
default_filament_profile = Geeetech PLA @Geeetech;
start_gcode = ;Geeetech M1 official wiki URL：https://www.geeetech.com/wiki/index.php/Geeetech_M1_3D_printer \nM104 S[first_layer_temperature] ; Set Hotend Temperature\nM190 S[first_layer_bed_temperature] ; Wait for Bed Temperature\nM109 S[first_layer_temperature]  ; Wait for Hotend Temperature\nG92 E0 ; Reset Extruder\nG28 ; Home all axes\nM107 ;Off Main Fan\nM300 S2500 P1000 ;Play a short tune\nG1 Z0.28 ;Move Z Axis up little to prevent scratching of Heat Bed\nG92 E0 ;Reset Extruder\nG1 Y3 F2400 ;Move to start position\nG1 X75 E40 F500 ;Draw a filament line\nG92 E0 ;Reset Extruder\n;G1 E-0.2 F3000 ;Retract a little\nG1 Z2.0 F3000 ;Move Z Axis up little to prevent scratching of Heat Bed\nG1 X70 Y3 Z0.27 F3000 ;Quickly wipe away from the filament line\nG92 E0 ;Reset Extruder
printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_Geeetech\nPRINTER_MODEL_M1

