[print:*common predator*]
spiral_vase = 0
top_solid_min_thickness = 0.8
bottom_solid_min_thickness = 0.6
extra_perimeters = 0
ensure_vertical_shell_thickness = 1
avoid_crossing_perimeters = 0
thin_walls = 0
overhangs = 1
seam_position = nearest
external_perimeters_first = 0
fill_density = 20%
external_fill_pattern = rectilinear
infill_every_layers = 1
infill_only_where_needed = 0
solid_infill_every_layers = 0
fill_angle = 45
solid_infill_below_area = 20
bridge_angle = 0
only_retract_when_crossing_perimeters = 0
infill_first = 0
skirts = 1
skirt_distance = 4
skirt_height = 1
min_skirt_length = 8
brim_width = 0
support_material = 0
support_material_auto = 1
support_material_threshold = 50
support_material_enforce_layers = 0
raft_layers = 0
support_material_contact_distance = 0.1
support_material_pattern = rectilinear
support_material_with_sheath = 0
support_material_spacing = 2
support_material_angle = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_contact_loops = 0
support_material_buildplate_only = 0
support_material_xy_spacing = 60%
dont_support_bridges = 1
support_material_synchronize_layers = 0
travel_speed = 94
first_layer_speed = 15
perimeter_acceleration = 0
infill_acceleration = 0
bridge_acceleration = 0
first_layer_acceleration = 0
default_acceleration = 0
max_volumetric_speed = 15
perimeter_extruder = 1
infill_extruder = 1
solid_infill_extruder = 1
support_material_extruder = 0
support_material_interface_extruder = 0
ooze_prevention = 0
standby_temperature_delta = -5
wipe_tower = 0
wipe_tower_x = 170
wipe_tower_y = 140
wipe_tower_width = 60
wipe_tower_rotation_angle = 0
wipe_tower_bridging = 10
interface_shells = 0
bridge_flow_ratio = 0.8
resolution = 0
xy_size_compensation = 0
elefant_foot_compensation = 0.2
clip_multipart_objects = 1
complete_objects = 0
gcode_comments = 0
output_filename_format = {input_filename_base}.gcode
post_process =
notes =
max_volumetric_extrusion_rate_slope_negative = 0
max_volumetric_extrusion_rate_slope_positive = 0
print_settings_id =

# Common print preset
