[print:*common predator 0.4 nozzle*]
inherits = *common predator*
first_layer_height = 0.16
infill_overlap = 25%
compatible_printers_condition = printer_notes=~/.*PRINTER_VENDOR_ANYCUBIC.*/ and printer_notes=~/.*PRINTER_MODEL_PREDATOR.*/ and printer_notes=~/.*PRINTER_HAS_BOWDEN.*/ and nozzle_diameter[0]==0.4

# Common print preset
